name: Update and Deploy Shiny App

on:
  schedule:
    - cron: '0 9 * * *'  # runs daily at 9 AM UTC (2 AM PDT)
  workflow_dispatch:      # allows manual trigger in GitHub Actions UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out repo
        uses: actions/checkout@v3
        
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          build-essential \
          libssl-dev \
          libcurl4-openssl-dev \
          libxml2-dev \
          libcppunit-dev \
          r-base-dev


        
      - name: Add geospatial dependencies
        run: |
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev \
            libpng-dev


      - name: 📦 Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Ensure cache directories exist
        run: |
          mkdir -p ~/.local/share/renv
          mkdir -p ~/.cache/R/renv
        
      - name: Cache R packages 
        uses: actions/cache@v3 
        with: 
          path: |
            ~/.local/share/renv
            ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }} 
          restore-keys: | 
            ${{ runner.os }}-renv-
            
      - name: Enable source repositories
        run: |
          sudo sed -i 's/^# deb-src/deb-src/' /etc/apt/sources.list
          sudo apt-get-update
            
      - name: Manually install R headers
        run: |
          sudo apt-get source r-base-core
          sudo cp r-base*/src/include/*.h /usr/local/include/
          
      - name: Check for R.h header
        run: |
          echo "Checking for R.h..."
          find / -name R.h 2>/dev/null || echo "R.h not found"
      
      - name: Restore R environment
        run: |
          Rscript -e 'install.packages("renv", repos="https://cloud.r-project.org")'
          Rscript -e 'renv::restore()'

      
      - name: 🛠️ Run data update script
        run: Rscript ptagis_processing.R
        

      - name: 🚀 Deploy to shinyapps.io
        env:
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript -e 'rsconnect::setAccountInfo(name = "elifelts", token = Sys.getenv("SHINYAPPS_TOKEN"), secret = Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e 'rsconnect::deployApp(appDir = ".", forceUpdate = TRUE, appFiles = list.files
